/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhadat;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import javafx.print.Collation;
import javax.swing.JOptionPane;

/**
 *
 * @author trant
 */
public class QLNhaDat_form extends javax.swing.JFrame {

    /**
     * Creates new form QLNhaDat_form
     */
    public QLNhaDat_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btn_gd92013 = new javax.swing.JButton();
        tf_dongia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        combo_loainhap = new javax.swing.JComboBox<>();
        tf_dientich = new javax.swing.JTextField();
        combo_loainha = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btn_luu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_hienthi = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tf_maso = new javax.swing.JTextField();
        btn_xem = new javax.swing.JButton();
        tf_diachi = new javax.swing.JTextField();
        btn_soluongtungloai = new javax.swing.JButton();
        tf_ngaygd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_TBTTdat = new javax.swing.JButton();
        comno_loaidat = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Ngày giao dịch");

        btn_gd92013.setText("Giao Dịch tháng 9 2013");
        btn_gd92013.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gd92013ActionPerformed(evt);
            }
        });

        jLabel8.setText("Loại nhà: ");

        jLabel3.setText("Đơn giá");

        combo_loainhap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhà", "Đất" }));
        combo_loainhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_loainhapActionPerformed(evt);
            }
        });

        combo_loainha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thường", "Cao cấp" }));

        jLabel4.setText("Diện tích");

        btn_luu.setText("Lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        jLabel5.setText("Loại:");

        ta_hienthi.setColumns(20);
        ta_hienthi.setRows(5);
        jScrollPane1.setViewportView(ta_hienthi);

        jLabel6.setText("Loại đất:");

        jLabel1.setText("Mã Số");

        btn_xem.setText("Xem");
        btn_xem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xemActionPerformed(evt);
            }
        });

        btn_soluongtungloai.setText("Số lượng từng loại");
        btn_soluongtungloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_soluongtungloaiActionPerformed(evt);
            }
        });

        jLabel7.setText("Địa chỉ: ");

        btn_TBTTdat.setText("TB Thành tiền (Đất)");
        btn_TBTTdat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TBTTdatActionPerformed(evt);
            }
        });

        comno_loaidat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));

        jButton1.setText("Tìm kiếm theo ms");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sort theo ms");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Sort theo dt");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Thành tiền lớn nhất theo loại");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Tìm kiếm theo (Loai, Diện tích, Đơn giá) ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Số lượng loại nhà và đất");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Search theo tháng + năm");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_dientich, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_maso, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_ngaygd, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(btn_luu))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_xem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(combo_loainhap, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comno_loaidat, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(48, 48, 48)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(combo_loainha, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton1)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_dongia, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_soluongtungloai)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btn_TBTTdat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_gd92013, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton4))))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tf_maso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(combo_loainhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_ngaygd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(comno_loaidat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jButton7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(combo_loainha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(tf_dongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_gd92013))
                    .addComponent(btn_soluongtungloai))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_TBTTdat)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_dientich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_luu)
                            .addComponent(btn_xem)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton6)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gd92013ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gd92013ActionPerformed
        // TODO add your handling code here:
        ta_hienthi.setText("");
        for (QLNhaDat nhaDat : listnhadat) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String str = sdf.format(nhaDat.getNgay_gd());
            String[] dateGiaoDichDat = str.split("/");
            if (dateGiaoDichDat[1].equals("09") && dateGiaoDichDat[2].equals("2013")) {
                ta_hienthi.append(nhaDat.toString() + "\n");
            }

        }
    }//GEN-LAST:event_btn_gd92013ActionPerformed

    private void combo_loainhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_loainhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_loainhapActionPerformed

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        // TODO add your handling code here:
        if (combo_loainhap.getSelectedItem().toString().equals("Nhà")) {
            Nha nha = new Nha();
            nha.setMa_gd(tf_maso.getText());
            SimpleDateFormat time = new SimpleDateFormat("dd/MM/yyyy");
            try {
                nha.setNgay_gd(time.parse(tf_ngaygd.getText()));
            } catch (Exception e) {
            }
            nha.setDongia(Integer.parseInt(tf_dongia.getText()));
            nha.setLoainha(combo_loainha.getSelectedItem().toString());
            nha.setDiachi(tf_diachi.getText());
            nha.setDientich(Integer.parseInt(tf_dientich.getText()));
            if (!listnhadat.contains(nha)) {
                listnhadat.add(nha);
                ta_hienthi.setText("lưu thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Trùng mã số", "thong bao", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            Dat dat = new Dat();
            dat.setMa_gd(tf_maso.getText());
            SimpleDateFormat time = new SimpleDateFormat("dd/mm/yyyy");
            try {
                dat.setNgay_gd(time.parse(tf_ngaygd.getText()));
            } catch (Exception e) {
            }
            dat.setDongia(Integer.parseInt(tf_dongia.getText()));
            dat.setDientich(Integer.parseInt(tf_dientich.getText()));
            dat.setLoaidat(comno_loaidat.getSelectedItem().toString());
            if (!listnhadat.contains(dat)) {
                listnhadat.add(dat);
                ta_hienthi.setText("lưu thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Trùng mã số", "thong bao", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_luuActionPerformed

    private void btn_xemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xemActionPerformed
        // TODO add your handling code here:
        ta_hienthi.setText("");
        for (QLNhaDat nhaDat : listnhadat) {
            ta_hienthi.append(nhaDat.toString() + "\n");
        }
    }//GEN-LAST:event_btn_xemActionPerformed

    private void btn_soluongtungloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_soluongtungloaiActionPerformed
        // TODO add your handling code here:
        for (QLNhaDat nhaDat : listnhadat) {
            if (nhaDat.getClass().getSimpleName().equals("Nha")) {
                sl_nha++;
            } else {
                sl_dat++;
            }
        }
        ta_hienthi.setText("Số lượng đất: " + sl_dat + "\n" + "Số lượng nhà: " + sl_nha);
    }//GEN-LAST:event_btn_soluongtungloaiActionPerformed

    private void btn_TBTTdatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TBTTdatActionPerformed
        // TODO add your handling code here:
        double tb_thanhtien = 0;
        for (QLNhaDat nhaDat : listnhadat) {
            if (nhaDat.getClass().getSimpleName().equals("Dat")) {
                tb_thanhtien += nhaDat.ThanhTien();
            }
        }
        ta_hienthi.setText("Trung bình thành tiền đất: " + (tb_thanhtien / sl_dat));
    }//GEN-LAST:event_btn_TBTTdatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (listnhadat.size() == 0) {
            this.ta_hienthi.setText("danh sách xe rỗng");
        } else {
            for (QLNhaDat nd : listnhadat) {
                if (nd.getMa_gd().equals(this.tf_maso.getText())) {
                    this.ta_hienthi.setText(nd.toString());
                    break;
                } else {
                    this.ta_hienthi.setText("không có xe trùng mã số " + this.tf_maso.getText());
                }
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Collections.sort(listnhadat, new Comparator<QLNhaDat>() {
            @Override
            public int compare(QLNhaDat o1, QLNhaDat o2) {
                return o1.getMa_gd().compareTo(o2.getMa_gd());
            }
        });
        ta_hienthi.setText("");
        for (QLNhaDat nhaDat : listnhadat) {
            ta_hienthi.append(nhaDat.toString() + "\n");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Collections.sort(listnhadat, new Comparator<QLNhaDat>() {
            @Override
            public int compare(QLNhaDat o1, QLNhaDat o2) {
                return o1.getDientich() > o2.getDientich() ? 1
                        : o1.getDientich() < o2.getDientich() ? -1 : 0;
            }
        });
        ta_hienthi.setText("");
        for (QLNhaDat nhaDat : listnhadat) {
            ta_hienthi.append(nhaDat.toString() + "\n");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.ta_hienthi.setText("");
        double maxdat=0;
        double maxnha=0;
        for (QLNhaDat qLNhaDat : listnhadat) {
            if (qLNhaDat.getClass().getSimpleName().equals("Nha")) {
                if (qLNhaDat.ThanhTien()>maxnha) {
                    maxnha = qLNhaDat.ThanhTien();
                }
            }
            else{
                if (qLNhaDat.ThanhTien()>maxnha) {
                    maxdat = qLNhaDat.ThanhTien();
                }
            }
        }
        this.ta_hienthi.setText("Nhà có thành tiền lớn nhất: " + maxnha +"\n" + "Đất có thành tiền lớn nhất: " + maxdat);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String dt = tf_dientich.getText();
        String dg = tf_dongia.getText();
        if (combo_loainhap.getSelectedItem().toString().equals("Nhà")) {
            if (dt.equals("") && dg.equals("")) {
                this.ta_hienthi.setText("vui long nhập diện tích, đơn giá");
            }
            if (dg.equals("") && !dt.equals("")) {
                for (QLNhaDat qLNhaDat : listnhadat) {
                    if (qLNhaDat.getClass().getSimpleName().equals("Nha")) {
                        if (dt.equals(qLNhaDat.getDientich() + "")) {
                            this.ta_hienthi.setText(qLNhaDat.toString());
                        } else {
                            this.ta_hienthi.setText("ko có dt: " + dt);
                        }
                    }
                }
            }
            if (dt.equals("") && !dg.equals("")) {
                for (QLNhaDat qLNhaDat : listnhadat) {
                    if (qLNhaDat.getClass().getSimpleName().equals("Nha")) {
                        if (dg.equals(qLNhaDat.getDongia() + "")) {
                            this.ta_hienthi.setText(qLNhaDat.toString());
                        } else {
                            this.ta_hienthi.setText("ko có dg: " + dg);
                        }
                    }
                }
            }
            if (!dt.equals("") && !dg.equals("")) {
                for (QLNhaDat qLNhaDat : listnhadat) {
                    if (qLNhaDat.getClass().getSimpleName().equals("Nha")) {
                        if (dt.equals(qLNhaDat.getDientich() + "") && dg.equals(qLNhaDat.getDongia() + "")) {
                            this.ta_hienthi.setText(qLNhaDat.toString());
                        } else {
                            this.ta_hienthi.setText("ko có dt: " + dt + " và don giá" + dg);
                        }
                    }
                }
            }
        } ////////////tìm theo Dat
        else {
            if (dt.equals("") && dg.equals("")) {
                this.ta_hienthi.setText("vui long nhập diện tích, đơn giá");
            }
            if (dg.equals("") && !dt.equals("")) {
                for (QLNhaDat qLNhaDat : listnhadat) {
                    if (qLNhaDat.getClass().getSimpleName().equals("Dat")) {
                        if (dt.equals(qLNhaDat.getDientich() + "")) {
                            this.ta_hienthi.setText(qLNhaDat.toString());
                        } else {
                            this.ta_hienthi.setText("ko có dt: " + dt);
                        }
                    }
                }
            }
            if (dt.equals("") && !dg.equals("")) {
                for (QLNhaDat qLNhaDat : listnhadat) {
                    if (qLNhaDat.getClass().getSimpleName().equals("Dat")) {
                        if (dg.equals(qLNhaDat.getDongia() + "")) {
                            this.ta_hienthi.setText(qLNhaDat.toString());
                        } else {
                            this.ta_hienthi.setText("ko có dg: " + dg);
                        }
                    }
                }
            }
            if (!dt.equals("") && !dg.equals("")) {
                for (QLNhaDat qLNhaDat : listnhadat) {
                    if (qLNhaDat.getClass().getSimpleName().equals("Dat")) {
                        if (dt.equals(qLNhaDat.getDientich() + "") && dg.equals(qLNhaDat.getDongia() + "")) {
                            this.ta_hienthi.setText(qLNhaDat.toString());
                        } else {
                            this.ta_hienthi.setText("ko có dt: " + dt + " và don giá" + dg);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int a = 0;
        int b = 0;
        int c = 0;
        int caocap = 0;
        int thuong = 0;
        for (QLNhaDat nhadat : listnhadat) {
            /*    {*/
            if ((nhadat.getClass().getSimpleName().equals("Dat"))) {
                if (nhadat.loai().equals("A")) {
                    a++;
                } else if (nhadat.loai().equals("B")) {
                    b++;
                } else {
                    c++;
                }
            } else {
                if (nhadat.loai().equals("Cao cấp")) {
                    caocap++;
                } else {
                    thuong++;
                }
            }
        }
        this.ta_hienthi.append("Số lượng dat A được mua: " + a + "\n");
        this.ta_hienthi.append("Số lượng dat B được mua: " + b + "\n");
        this.ta_hienthi.append("Số lượng dat C được mua: " + c + "\n");
        this.ta_hienthi.append("Số lượng nha Cao Cap được mua: " + caocap + "\n");
        this.ta_hienthi.append("Số lượng nha Thuong được mua: " + thuong + "\n");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Date date = null;
        SimpleDateFormat time = new SimpleDateFormat("MM/yyyy");
        try {
            date = time.parse(tf_ngaygd.getText());
        } catch (Exception e) {
        }
        this.ta_hienthi.setText("");
        for (QLNhaDat qlnd : listnhadat) {
            if (date.getMonth() == (qlnd.getNgay_gd()).getMonth() && date.getYear() == (qlnd.getNgay_gd()).getYear()) {
                this.ta_hienthi.append(qlnd.toString());
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNhaDat_form.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNhaDat_form.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNhaDat_form.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNhaDat_form.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLNhaDat_form().setVisible(true);
            }
        });
    }
    ArrayList<QLNhaDat> listnhadat = new ArrayList<>();
    int sl_nha = 0;
    int sl_dat = 0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_TBTTdat;
    private javax.swing.JButton btn_gd92013;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_soluongtungloai;
    private javax.swing.JButton btn_xem;
    private javax.swing.JComboBox<String> combo_loainha;
    private javax.swing.JComboBox<String> combo_loainhap;
    private javax.swing.JComboBox<String> comno_loaidat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta_hienthi;
    private javax.swing.JTextField tf_diachi;
    private javax.swing.JTextField tf_dientich;
    private javax.swing.JTextField tf_dongia;
    private javax.swing.JTextField tf_maso;
    private javax.swing.JTextField tf_ngaygd;
    // End of variables declaration//GEN-END:variables
}
