/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendien;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author trant
 */
public class QlTienDien_form extends javax.swing.JFrame {

    /**
     * Creates new form QlTienDien_form
     */
    public QlTienDien_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_maso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_hoten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_date = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_kw = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_dongia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_dinhmuc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_quocgia = new javax.swing.JTextField();
        combo_loaikhach = new javax.swing.JComboBox<>();
        combo_doituong = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_hienthi = new javax.swing.JTextArea();
        btn_luu = new javax.swing.JButton();
        btn_xem = new javax.swing.JButton();
        btn_soluongtungKH = new javax.swing.JButton();
        btn_TTnuocngoai = new javax.swing.JButton();
        btn_hdlonhat = new javax.swing.JButton();
        btn_hdnhonhat = new javax.swing.JButton();
        btn_kw500 = new javax.swing.JButton();
        btn_nhohondinhmuc = new javax.swing.JButton();
        btn_searchbyyear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã số");

        jLabel2.setText("Họ tên");

        jLabel3.setText("Ngày ra hóa đơn");

        jLabel4.setText("Số kw");

        jLabel5.setText("Đơn giá");

        jLabel6.setText("Khách");

        jLabel7.setText("Đối tượng khách");

        jLabel8.setText("Định mức");

        jLabel9.setText("Quốc gia");

        combo_loaikhach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khách Việt Nam", "Khách Nước Ngoài" }));

        combo_doituong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sinh hoạt", "Kinh doanh", "Sản xuất" }));

        ta_hienthi.setColumns(20);
        ta_hienthi.setRows(5);
        jScrollPane1.setViewportView(ta_hienthi);

        btn_luu.setText("Lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        btn_xem.setText("Xem");
        btn_xem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xemActionPerformed(evt);
            }
        });

        btn_soluongtungKH.setText("Số lượng từng loại KH");
        btn_soluongtungKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_soluongtungKHActionPerformed(evt);
            }
        });

        btn_TTnuocngoai.setText("TB thành tiền khách nc ngoài");
        btn_TTnuocngoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TTnuocngoaiActionPerformed(evt);
            }
        });

        btn_hdlonhat.setText("Hóa đơn lớn nhất");
        btn_hdlonhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hdlonhatActionPerformed(evt);
            }
        });

        btn_hdnhonhat.setText("Hóa đơn nhỏ nhất");
        btn_hdnhonhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hdnhonhatActionPerformed(evt);
            }
        });

        btn_kw500.setText("KH có kw > dm = 500");
        btn_kw500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kw500ActionPerformed(evt);
            }
        });

        btn_nhohondinhmuc.setText("KH kw<định mức");
        btn_nhohondinhmuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nhohondinhmucActionPerformed(evt);
            }
        });

        btn_searchbyyear.setText("Search theo tháng + năm");
        btn_searchbyyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchbyyearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(70, 70, 70)
                                .addComponent(tf_maso, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(70, 70, 70)
                                .addComponent(tf_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_date, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(166, 166, 166)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_dinhmuc, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(combo_loaikhach, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combo_doituong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addComponent(jLabel9)
                        .addGap(70, 70, 70)
                        .addComponent(tf_quocgia, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_dongia, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(70, 70, 70)
                                .addComponent(tf_kw, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_hdlonhat)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_luu)
                                .addGap(18, 18, 18)
                                .addComponent(btn_xem)))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_hdnhonhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_soluongtungKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_kw500, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_TTnuocngoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_searchbyyear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_nhohondinhmuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_maso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(tf_quocgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(combo_loaikhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(combo_doituong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tf_dinhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_kw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_dongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btn_luu)
                    .addComponent(btn_xem)
                    .addComponent(btn_soluongtungKH)
                    .addComponent(btn_TTnuocngoai)
                    .addComponent(btn_searchbyyear))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_hdlonhat)
                    .addComponent(btn_hdnhonhat)
                    .addComponent(btn_kw500)
                    .addComponent(btn_nhohondinhmuc))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        // TODO add your handling code here:
        if (combo_loaikhach.getSelectedItem().toString().equals("Khách Việt Nam")) {
            KhachVn vn = new KhachVn();
            vn.setMaso(tf_maso.getText());
            vn.setHoten(tf_hoten.getText());
            SimpleDateFormat time = new SimpleDateFormat("dd/MM/yyyy");
            try {
                vn.setNgayrahd(time.parse(tf_date.getText()));
            } catch (Exception e) {
            }
            vn.setSo_kw(Integer.parseInt(tf_kw.getText()));
            vn.setDongia(Integer.parseInt(tf_dongia.getText()));
            vn.setLoaikh(combo_doituong.getSelectedItem().toString());
            vn.setDinhmuc(Integer.parseInt(tf_dinhmuc.getText()));
            if (!listTienDien.contains(vn)) {
                listTienDien.add(vn);
                ta_hienthi.setText("lưu thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Trùng mã số", "thong bao", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            KhachNgoai nn = new KhachNgoai();
            nn.setMaso(tf_maso.getText());
            nn.setHoten(tf_hoten.getText());
            SimpleDateFormat time = new SimpleDateFormat("dd/MM/yyyy");
            try {
                nn.setNgayrahd(time.parse(tf_date.getText()));
            } catch (Exception e) {
            }
            nn.setSo_kw(Integer.parseInt(tf_kw.getText()));
            nn.setDongia(Integer.parseInt(tf_dongia.getText()));
            nn.setQuocgia(tf_quocgia.getText());
            if (!listTienDien.contains(nn)) {
                listTienDien.add(nn);
                ta_hienthi.setText("lưu thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Trùng mã số", "thong bao", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_luuActionPerformed

    private void btn_xemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xemActionPerformed
        // TODO add your handling code here:
        ta_hienthi.setText("");
        for (QlTienDien qlTienDien : listTienDien) {
            ta_hienthi.append(qlTienDien.toString() + "\n");
        }
    }//GEN-LAST:event_btn_xemActionPerformed

    private void btn_soluongtungKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_soluongtungKHActionPerformed
        // TODO add your handling code here:
        int sl_VN = 0;
        int sl_NN = 0;
        for (QlTienDien qlTienDien : listTienDien) {
            if (qlTienDien.getClass().getSimpleName().equals("KhachVn")) {
                sl_VN++;
            } else {
                sl_NN++;
            }
        }
        ta_hienthi.setText("Số lượng khách Vn: " + sl_VN + "\n" + "Số lượng khách NN: " + sl_NN);

    }//GEN-LAST:event_btn_soluongtungKHActionPerformed

    private void btn_TTnuocngoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TTnuocngoaiActionPerformed
        // TODO add your handling code here:
        double thanhtien = 0;
        int sl = 0;
        for (QlTienDien qlTienDien : listTienDien) {
            if (qlTienDien.getClass().getSimpleName().equals("KhachNgoai")) {
                thanhtien += qlTienDien.ThanhTien();
                sl++;
            }
        }
        ta_hienthi.setText("trung bình thành tiền khách nước ngoài: " + (thanhtien / sl));
    }//GEN-LAST:event_btn_TTnuocngoaiActionPerformed

    private void btn_hdlonhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hdlonhatActionPerformed
        // TODO add your handling code here:
        Collections.sort(listTienDien, new Comparator<QlTienDien>() {
            @Override
            public int compare(QlTienDien o1, QlTienDien o2) {
                return o1.ThanhTien() > o2.ThanhTien() ? 1
                        : o1.ThanhTien() < o2.ThanhTien() ? -1 : 0;
            }
        });
        int i = listTienDien.size() - 1;
        ta_hienthi.setText("Khách hàng có hóa đơn lớn nhất: " + listTienDien.get(i));
    }//GEN-LAST:event_btn_hdlonhatActionPerformed

    private void btn_hdnhonhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hdnhonhatActionPerformed
        // TODO add your handling code here:
        Collections.sort(listTienDien, new Comparator<QlTienDien>() {
            @Override
            public int compare(QlTienDien o2, QlTienDien o1) {
                return o1.ThanhTien() > o2.ThanhTien() ? 1
                        : o1.ThanhTien() < o2.ThanhTien() ? -1 : 0;
            }
        });
        int i = listTienDien.size() - 1;
        ta_hienthi.setText("Khách hàng có hóa đơn nhỏ nhất: " + listTienDien.get(i));
    }//GEN-LAST:event_btn_hdnhonhatActionPerformed

    private void btn_kw500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kw500ActionPerformed
        // TODO add your handling code here:
        this.ta_hienthi.setText("");
        for (QlTienDien qlTienDien : listTienDien) {
            if (qlTienDien.getClass().getSimpleName().equals("KhachVn")) {
                if (qlTienDien.getSo_kw() - ((KhachVn) qlTienDien).getDinhmuc() > 500) {
                    this.ta_hienthi.append("Hóa đơn có kw lớn hơn định mức 500kw: " + "\n" + qlTienDien.toString());
                }
            }
        }


    }//GEN-LAST:event_btn_kw500ActionPerformed
    private void btn_nhohondinhmucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nhohondinhmucActionPerformed
        // TODO add your handling code here:
        this.ta_hienthi.setText("");
        for (QlTienDien qlTienDien : listTienDien) {
            if (qlTienDien.getClass().getSimpleName().equals("KhachVn")) {
                if (((KhachVn) qlTienDien).getDinhmuc() > qlTienDien.getSo_kw()) {
                    this.ta_hienthi.append("Hóa đơn có kw nhỏ hơn định mức: " + "\n" + qlTienDien.toString());
                }
            }
        }
    }//GEN-LAST:event_btn_nhohondinhmucActionPerformed

    private void btn_searchbyyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchbyyearActionPerformed
        // TODO add your handling code here:
        Date date = null;
        SimpleDateFormat time = new SimpleDateFormat("MM/yyyy");
        try {
            date = time.parse(tf_date.getText());
        } catch (Exception e) {
        }
        this.ta_hienthi.setText("");
        for (QlTienDien qlTienDien : listTienDien) {
            if (date.getMonth() == (qlTienDien.getNgayrahd()).getMonth() && date.getYear() == (qlTienDien.getNgayrahd()).getYear()) {
                this.ta_hienthi.append(qlTienDien.toString());
            }
        }
    }//GEN-LAST:event_btn_searchbyyearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QlTienDien_form.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QlTienDien_form.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QlTienDien_form.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QlTienDien_form.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QlTienDien_form().setVisible(true);
            }
        });
    }
    ArrayList<QlTienDien> listTienDien = new ArrayList<>();


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_TTnuocngoai;
    private javax.swing.JButton btn_hdlonhat;
    private javax.swing.JButton btn_hdnhonhat;
    private javax.swing.JButton btn_kw500;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_nhohondinhmuc;
    private javax.swing.JButton btn_searchbyyear;
    private javax.swing.JButton btn_soluongtungKH;
    private javax.swing.JButton btn_xem;
    private javax.swing.JComboBox<String> combo_doituong;
    private javax.swing.JComboBox<String> combo_loaikhach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta_hienthi;
    private javax.swing.JTextField tf_date;
    private javax.swing.JTextField tf_dinhmuc;
    private javax.swing.JTextField tf_dongia;
    private javax.swing.JTextField tf_hoten;
    private javax.swing.JTextField tf_kw;
    private javax.swing.JTextField tf_maso;
    private javax.swing.JTextField tf_quocgia;
    // End of variables declaration//GEN-END:variables
}
