/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package giaodich;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author trant
 */
public class GiaoDichForm extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDichForm
     */
    public GiaoDichForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_maso = new javax.swing.JTextField();
        tf_ngaygd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_dongia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_soluong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_loaivang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_tigia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        combo_loainhap = new javax.swing.JComboBox<>();
        combo_loaitien = new javax.swing.JComboBox<>();
        btn_luu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_hienthi = new javax.swing.JTextArea();
        btn_xem = new javax.swing.JButton();
        btn_soluongtungloai = new javax.swing.JButton();
        btn_TBTTtiente = new javax.swing.JButton();
        btn_dongia1ty = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã Số");

        jLabel2.setText("Ngày giao dịch");

        jLabel3.setText("Đơn giá");

        jLabel4.setText("Số lượng");

        jLabel5.setText("Loại:");

        jLabel6.setText("Loại vàng:");

        jLabel7.setText("Tỉ giá");

        jLabel8.setText("Loại tiền tệ");

        combo_loainhap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vàng", "Tiền" }));
        combo_loainhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_loainhapActionPerformed(evt);
            }
        });

        combo_loaitien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "VND", "EURO" }));

        btn_luu.setText("Lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        ta_hienthi.setColumns(20);
        ta_hienthi.setRows(5);
        jScrollPane1.setViewportView(ta_hienthi);

        btn_xem.setText("Xem");
        btn_xem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xemActionPerformed(evt);
            }
        });

        btn_soluongtungloai.setText("Số lượng từng loại");
        btn_soluongtungloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_soluongtungloaiActionPerformed(evt);
            }
        });

        btn_TBTTtiente.setText("TB Thành tiền (tiền tệ)");
        btn_TBTTtiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TBTTtienteActionPerformed(evt);
            }
        });

        btn_dongia1ty.setText("Đơn giá > 1ty");
        btn_dongia1ty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dongia1tyActionPerformed(evt);
            }
        });

        jButton1.setText("Tìm kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sort theo ms");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_dongia, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_maso, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_ngaygd, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_loaivang, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(combo_loainhap, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_tigia, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(combo_loaitien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addContainerGap(62, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btn_luu)
                        .addGap(54, 54, 54)
                        .addComponent(btn_xem)
                        .addGap(54, 54, 54)
                        .addComponent(btn_soluongtungloai)
                        .addGap(62, 62, 62)
                        .addComponent(btn_TBTTtiente)
                        .addGap(27, 27, 27)
                        .addComponent(btn_dongia1ty))))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1087, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_tigia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(combo_loaitien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tf_maso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(combo_loainhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_ngaygd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(tf_loaivang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_dongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_luu)
                            .addComponent(btn_xem)
                            .addComponent(btn_soluongtungloai)
                            .addComponent(btn_TBTTtiente)
                            .addComponent(btn_dongia1ty))))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        // TODO add your handling code here:
        if (combo_loainhap.getSelectedItem().toString().equals("Vàng")) {
            Vang vang = new Vang();
            vang.setMa_gd(tf_maso.getText());
            SimpleDateFormat time = new SimpleDateFormat("dd/mm/yyyy");
            try {
                vang.setNgay_gd(time.parse(tf_ngaygd.getText()));
            } catch (Exception e) {
            }
            vang.setDongia(Integer.parseInt(tf_dongia.getText()));
            vang.setSoluong(Integer.parseInt(tf_soluong.getText()));
            vang.setLoaivang(tf_loaivang.getText());
            if (!listgiaodich.contains(vang)) {
                listgiaodich.add(vang);
                ta_hienthi.setText("lưu thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Trùng mã số", "thong bao", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            TienTe tien = new TienTe();
            tien.setMa_gd(tf_maso.getText());
            SimpleDateFormat time = new SimpleDateFormat("dd/mm/yyyy");
            try {
                tien.setNgay_gd(time.parse(tf_ngaygd.getText()));
            } catch (Exception e) {
            }
            tien.setDongia(Integer.parseInt(tf_dongia.getText()));
            tien.setSoluong(Integer.parseInt(tf_soluong.getText()));
            tien.setTigia(Float.parseFloat(tf_tigia.getText()));
            tien.setLoaitien(combo_loaitien.getSelectedItem().toString());
            if (!listgiaodich.contains(tien)) {
                listgiaodich.add(tien);
                ta_hienthi.setText("lưu thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Trùng mã số", "thong bao", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_luuActionPerformed

    private void btn_xemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xemActionPerformed
        // TODO add your handling code here:
        ta_hienthi.setText("");
        for (QLGiaodich giaodich : listgiaodich) {
            ta_hienthi.append(giaodich.toString() + "\n");
        }
    }//GEN-LAST:event_btn_xemActionPerformed

    private void btn_soluongtungloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_soluongtungloaiActionPerformed
        // TODO add your handling code here:
        for (QLGiaodich giaodich : listgiaodich) {
            if (giaodich.getClass().getSimpleName().equals("Vang")) {
                sl_vang++;
                vang+= giaodich.getSoluong();
            } else {
                sl_tien++;
                tien+= giaodich.getSoluong();
            }
        }
        ta_hienthi.setText("Số lượng vàng: " + sl_vang + "\n" + "Số lượng tiền tệ: " + sl_tien);
    }//GEN-LAST:event_btn_soluongtungloaiActionPerformed

    private void btn_TBTTtienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TBTTtienteActionPerformed
        // TODO add your handling code here:
        double tb_thanhtien = 0;
        for (QLGiaodich giaodich : listgiaodich) {
            if (giaodich.getClass().getSimpleName().equals("TienTe")) {
                tb_thanhtien += giaodich.ThanhTien();
            }
        }
        ta_hienthi.setText("Trung bình thành tiền Tiền tệ: " + (tb_thanhtien / sl_tien));
    }//GEN-LAST:event_btn_TBTTtienteActionPerformed

    private void btn_dongia1tyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dongia1tyActionPerformed
        // TODO add your handling code here:
        ta_hienthi.setText("");
        for (QLGiaodich qLGiaodich : listgiaodich) {
            if (qLGiaodich.getDongia() > 1000000000) {
                ta_hienthi.append(qLGiaodich.toString() + "\n");
            }
        }
    }//GEN-LAST:event_btn_dongia1tyActionPerformed

    private void combo_loainhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_loainhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_loainhapActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (listgiaodich.size() == 0) {
            this.ta_hienthi.setText("danh sách xe rỗng");
        } else {
            for (QLGiaodich gd : listgiaodich) {
                if (gd.getMa_gd().equals(this.tf_maso.getText())) {
                    this.ta_hienthi.setText(gd.toString());
                    break;
                } else {
                    this.ta_hienthi.setText("không có xe trùng mã số " + this.tf_maso.getText());
                }
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDichForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDichForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDichForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDichForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDichForm().setVisible(true);
            }
        });
    }

    ArrayList<QLGiaodich> listgiaodich = new ArrayList<>();
    int sl_vang = 0;
    int sl_tien = 0;
    int tien = 0;
    int vang = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_TBTTtiente;
    private javax.swing.JButton btn_dongia1ty;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_soluongtungloai;
    private javax.swing.JButton btn_xem;
    private javax.swing.JComboBox<String> combo_loainhap;
    private javax.swing.JComboBox<String> combo_loaitien;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta_hienthi;
    private javax.swing.JTextField tf_dongia;
    private javax.swing.JTextField tf_loaivang;
    private javax.swing.JTextField tf_maso;
    private javax.swing.JTextField tf_ngaygd;
    private javax.swing.JTextField tf_soluong;
    private javax.swing.JTextField tf_tigia;
    // End of variables declaration//GEN-END:variables
}
